# Generated by Django 5.1.7 on 2025-03-27 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InterviewFAQ',
        ),
        migrations.RemoveField(
            model_name='mockinterview',
            name='question',
        ),
    ]
