# Generated by Django 5.1.7 on 2025-03-27 21:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0002_delete_interviewfaq_remove_mockinterview_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.TextField()),
                ('transcript', models.TextField()),
                ('audio_analysis', models.JSONField(blank=True, null=True)),
                ('content_analysis', models.JSONField(blank=True, null=True)),
                ('bert_analysis', models.JSONField(blank=True, null=True)),
                ('relevant_keywords', models.JSONField(blank=True, null=True)),
                ('missing_keywords', models.JSONField(blank=True, null=True)),
                ('suggestions', models.JSONField(blank=True, null=True)),
                ('strengths', models.JSONField(blank=True, null=True)),
                ('improvement_areas', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='MockInterview',
        ),
    ]
